(test
 (name test_codec)
 (modules test_codec)
 (libraries venice))

(test
 (name test_bytes)
 (modules test_bytes)
 (libraries venice))

(test
 (name test_jsonx)
 (modules test_jsonx)
 (libraries venice))

(test
 (name test_modelx)
 (modules test_modelx)
 (libraries venice))

(test
 (name test_paramsx)
 (modules test_paramsx)
 (libraries venice))

(test
 (name test_msgx)
 (modules test_msgx)
 (libraries venice))

(test
 (name test_headx)
 (modules test_headx)
 (libraries venice))

(test
 (name test_chatx)
 (modules test_chatx)
 (libraries venice))
