(test
 (name test_codec)
 (modules test_codec)
 (libraries venice))

(test
 (name test_bytes)
 (modules test_bytes)
 (libraries venice))

(test
 (name test_jsonx)
 (modules test_jsonx)
 (libraries venice))

(test
 (name test_modelx)
 (modules test_modelx)
 (libraries venice))

(test
 (name test_paramsx)
 (modules test_paramsx)
 (libraries venice))

(test
 (name test_msgx)
 (modules test_msgx)
 (libraries venice))

(test
 (name test_headx)
 (modules test_headx)
 (libraries venice))

(test
 (name test_chatx)
 (modules test_chatx)
 (libraries venice))

(test
 (name test_respx)
 (modules test_respx)
 (libraries venice))

(test
 (name test_ssex)
 (modules test_ssex)
 (libraries venice))

(test
 (name test_accx)
 (modules test_accx)
 (libraries venice))

(test
 (name test_streamx)
 (modules test_streamx)
 (libraries venice))

(test
 (name test_transport)
 (modules test_transport)
 (libraries venice unix))

(test
 (name test_curlx)
 (modules test_curlx)
 (libraries venice unix))

(test
 (name test_retryx)
 (modules test_retryx)
 (libraries venice))

(test
 (name test_clientx)
 (modules test_clientx)
 (libraries venice))

(test
 (name test_limbsx)
 (modules test_limbsx)
 (libraries venice))

(test
 (name test_hmacx)
 (modules test_hmacx)
 (libraries venice))

(test
 (name test_keccakx)
 (modules test_keccakx)
 (libraries venice))

(test
 (name test_p256x)
 (modules test_p256x)
 (libraries venice))

(test
 (name test_secpx)
 (modules test_secpx)
 (libraries venice))
