#!/usr/bin/env python3
"""M18 differential gate over lib/keccakx.ml.

Every keccak-256, SHA3-256 and Ethereum-address constant that
test/test_keccakx.ml pins is recomputed here from the INPUTS this file
embeds, by a keccak-p[1600, 24] written from FIPS 202 section 3 that the
OCaml unit shares no code with. A recomputed value must then sit
VERBATIM inside a CHECK ROW of the suite, which is the part a raw
substring test cannot give: a `must_contain` over the whole file text
also passes for a pin parked in a comment or in a let that no check ever
reads.

`strip_ocaml_comments` and the check-row matcher below are COPIED
verbatim from harness/diff_hmac.py (M17), which copied them from
harness/diff_limbs.py (M16). A shared module would change those files,
which is out of scope for M18. `pin()` here STRIPS the leading quoted
label of a row before it searches, so a pin parked in a row NAME can
never satisfy the oracle; the same three lines land in the two older
harnesses in this milestone, and the in-memory control at the end of
this file proves the stripping.

This oracle shares NO table with lib/keccakx.ml: the 24 round constants
are GENERATED by the LFSR of FIPS 202 3.2.5 and the 25 rho offsets by
the recurrence of 3.2.2, so a constant pasted wrongly on either side
turns the gate RED. Before any pin is read the sponge validates ITSELF
under the 0x06 domain byte against `hashlib.sha3_256`, a C
implementation that shares nothing with either side, on the empty
string, "abc", 200 bytes of 0xa3 and the ascending messages of 135, 136
and 137 bytes; a mismatch exits 1 on the spot.

The suite computes each digest from the inputs it holds, so an input
that drifts from this file turns a row false and the gate RED: the suite
and this oracle must agree on inputs AND outputs. `ascending first n` on
the suite side emits through Bytesx.of_codes, whose chr_in masks every
code with `land 255`, so for n above 256 the message is the WRAPPED
sequence (first + i) mod 256 and this file builds the same bytes.

The pins are (a) the five keccak-256 known-answer tests; (b) the seven
rate boundary lengths, where 135 is the single-byte pad, 136 the whole
extra block and 137 the second block, 271 to 273 the same three cases
one block later and 1000 the multi-block path; (c) the three SHA3-256
witnesses, each also compared to hashlib.sha3_256 inline; (d) the
Ethereum address of secp256k1's base point G, from Gx and Gy embedded
here as hex inputs; (e) the eight EIP-55 reference strings, each
recomputed from its own lowercase form.

Then two negative controls. The first: the corrupted twin of the empty
string's keccak-256 digest, its last nibble flipped, must be ABSENT from
the stripped text. The second is the matcher's own label stripping,
proven on a synthetic row held in memory: a digest that sits only in a
row NAME must be reported MISSING.

Standard library only: hashlib, pathlib, re, sys.
"""

import hashlib
import pathlib
import re
import sys

here = pathlib.Path(__file__).resolve().parent
root = here.parent
suite_path = root / "test" / "test_keccakx.ml"

fail = 0

MASK = (1 << 64) - 1
RATE = 136
HASH_LEN = 32


# ---------- the reference implementation, tables generated ----------


def round_constants() -> list:
    """FIPS 202 3.2.5: rc(t) from the 8-bit LFSR, 24 lane constants."""
    out = []
    lfsr = 1
    for _ in range(24):
        lane = 0
        for j in range(7):
            if lfsr & 1:
                lane ^= 1 << ((1 << j) - 1)
            lfsr <<= 1
            if lfsr & 0x100:
                lfsr ^= 0x171
        out.append(lane)
    return out


def rho_offsets() -> dict:
    """FIPS 202 3.2.2: the offsets from the (x, y) recurrence."""
    off = {(0, 0): 0}
    x, y = 1, 0
    for t in range(24):
        off[(x, y)] = ((t + 1) * (t + 2) // 2) % 64
        x, y = y, (2 * x + 3 * y) % 5
    return off


RC = round_constants()
RHO = rho_offsets()


def rotl(v: int, n: int) -> int:
    return ((v << n) | (v >> (64 - n))) & MASK if n else v


def keccak_f(lanes: list) -> list:
    """keccak-p[1600, 24]; lane (x, y) sits at index x + 5 * y."""
    for rc in RC:
        col = [
            lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20]
            for x in range(5)
        ]
        d = [col[(x - 1) % 5] ^ rotl(col[(x + 1) % 5], 1) for x in range(5)]
        lanes = [lanes[x + 5 * y] ^ d[x] for y in range(5) for x in range(5)]
        b = [0] * 25
        for y in range(5):
            for x in range(5):
                b[y + 5 * ((2 * x + 3 * y) % 5)] = rotl(lanes[x + 5 * y], RHO[(x, y)])
        lanes = [
            b[x + 5 * y] ^ ((~b[(x + 1) % 5 + 5 * y]) & b[(x + 2) % 5 + 5 * y] & MASK)
            for y in range(5)
            for x in range(5)
        ]
        lanes[0] = lanes[0] ^ rc
    return lanes


def pad(msg: bytes, domain: int) -> bytes:
    """The multi-rate pad at rate 136."""
    tail = len(msg) % RATE
    if tail == RATE - 1:
        return msg + bytes([domain | 0x80])
    return msg + bytes([domain]) + bytes(RATE - tail - 2) + bytes([0x80])


def sponge(msg: bytes, domain: int) -> bytes:
    lanes = [0] * 25
    block = pad(msg, domain)
    for start in range(0, len(block), RATE):
        chunk = block[start : start + RATE]
        for i in range(17):
            lanes[i] = lanes[i] ^ int.from_bytes(chunk[8 * i : 8 * i + 8], "little")
        lanes = keccak_f(lanes)
    out = b""
    for i in range(4):
        out = out + lanes[i].to_bytes(8, "little")
    return out[:HASH_LEN]


def keccak256(msg: bytes) -> str:
    return sponge(msg, 0x01).hex()


def sha3_256(msg: bytes) -> str:
    return sponge(msg, 0x06).hex()


def asc(n: int) -> bytes:
    """The suite's `ascending 0 n`, wrapped by Bytesx.chr_in's land 255."""
    return bytes((i % 256) for i in range(n))


# ---------- the self-check, before any pin is read ----------

SELF_CHECK = [b"", b"abc", b"\xa3" * 200, asc(135), asc(136), asc(137)]
bad = [m for m in SELF_CHECK if sha3_256(m) != hashlib.sha3_256(m).hexdigest()]
if bad:
    print("diff_keccak: sha3 self-check FAILED against hashlib on:")
    for m in bad:
        print(f"  message of {len(m)} bytes")
    sys.exit(1)
if len(RC) != 24 or RC[0] != 1 or len(RHO) != 25 or RHO[(0, 0)] != 0:
    print("diff_keccak: the generated tables are not the FIPS 202 tables")
    sys.exit(1)
if sorted(RHO[k] for k in RHO if k != (0, 0)) != sorted(
    set(RHO[k] for k in RHO if k != (0, 0))
) or min(RHO[k] for k in RHO if k != (0, 0)) < 1:
    print("diff_keccak: a generated rho offset leaves 1 .. 63")
    sys.exit(1)
print("diff_keccak: sha3 self-check ok")


# ---------- the suite matcher ----------


def strip_ocaml_comments(text: str) -> str:
    """Replace every (* ... *) comment with one space, nesting aware."""
    out = []
    depth = 0
    i = 0
    end = len(text)
    while i < end:
        if text.startswith("(*", i):
            depth += 1
            i += 2
            continue
        if text.startswith("*)", i) and depth > 0:
            depth -= 1
            i += 2
            out.append(" ")
            continue
        if depth == 0:
            out.append(text[i])
        i += 1
    return "".join(out)


ROW_START = re.compile(r'^\s*(?:\[\s*)?\(\s*"')
TOP_LEVEL = re.compile(r"^\S")


def check_rows(text: str) -> list:
    """Split the stripped suite into check rows.

    A row opens on an indented `( "label",` line and closes at the next
    row or at the next column-zero definition, so a constant sitting in
    a top-level let is outside every row.
    """
    rows = []
    current = None
    for line in text.splitlines():
        if ROW_START.match(line):
            if current is not None:
                rows.append("\n".join(current))
            current = [line]
        elif current is not None:
            if TOP_LEVEL.match(line):
                rows.append("\n".join(current))
                current = None
            else:
                current.append(line)
    if current is not None:
        rows.append("\n".join(current))
    return rows


if not suite_path.is_file():
    print(f"diff_keccak: the suite is missing: {suite_path}")
    sys.exit(1)

RAW = suite_path.read_text()
STRIPPED = strip_ocaml_comments(RAW)
ROWS = check_rows(STRIPPED)

if not ROWS:
    print("diff_keccak: no check row found in the suite; the oracle is vacuous")
    sys.exit(1)

LABEL = re.compile(r'^\s*(?:\[\s*)?\(\s*"(?:[^"\\]|\\.)*"')
BODIES = [LABEL.sub("", row, count=1) for row in ROWS]


def pin(name: str, needles: list) -> None:
    """Require every needle of a pin to sit inside one check row."""
    global fail
    missing = [x for x in needles if not any(x in body for body in BODIES)]
    for x in missing:
        print(f"diff_keccak: {name}: recomputed value is in no check row")
        print(f"  wanted: {x}")
    if missing:
        fail = 1
    else:
        print(f"diff_keccak: {name} ok")


def require(name: str, ok: bool) -> None:
    """A pure cryptographic fact about a pin, independent of the suite."""
    global fail
    if not ok:
        print(f"diff_keccak: {name}: the python recompute disagrees with itself")
        fail = 1


# ---------- pin (a): the keccak-256 known-answer tests ----------

NIST56 = b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"
KATS = [
    ("the empty string", b""),
    ("abc", b"abc"),
    ("hello", b"hello"),
    ("200 bytes of 0xa3", b"\xa3" * 200),
    ("the 56-byte message", NIST56),
]

EMPTY_KECCAK = keccak256(b"")
require(
    "pin a the empty string",
    EMPTY_KECCAK
    == "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
)
require("pin a length", len(NIST56) == 56)

for label, msg in KATS:
    digest = keccak256(msg)
    require(f"pin a keccak-256 of {label} length", len(digest) == 64)
    pin(f"pin a keccak-256 of {label}", [digest])

# ---------- pin (b): the rate boundaries ----------

BOUNDS = [135, 136, 137, 271, 272, 273, 1000]
require("pin b the single-byte pad case", 135 % RATE == RATE - 1)
require("pin b the whole extra block case", 136 % RATE == 0)
require("pin b the multi-block case", 1000 // RATE == 7 and 1000 % RATE == 48)

for n in BOUNDS:
    pin(f"pin b the ascending message of {n} bytes", [keccak256(asc(n))])

# ---------- pin (c): the SHA3-256 permutation witnesses ----------

WITNESS = [
    ("the empty string", b""),
    ("abc", b"abc"),
    ("200 bytes of 0xa3", b"\xa3" * 200),
]

require(
    "pin c the empty string",
    sha3_256(b"")
    == "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a",
)
require("pin c the domains differ", sha3_256(b"") != keccak256(b""))

for label, msg in WITNESS:
    digest = sha3_256(msg)
    require(
        f"pin c SHA3-256 of {label} against hashlib",
        digest == hashlib.sha3_256(msg).hexdigest(),
    )
    pin(f"pin c SHA3-256 of {label}", [digest])

# ---------- pin (d): the Ethereum address of G ----------

GX = "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
GY = "483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"


def address_of(pubkey: bytes) -> str:
    return keccak256(pubkey)[-40:]


def checksum(body: str) -> str:
    """EIP-55 over a 40-character lowercase body."""
    digest = keccak256(body.encode("ascii"))
    return "0x" + "".join(
        c.upper() if int(digest[i], 16) >= 8 else c for i, c in enumerate(body)
    )


G_ADDRESS = address_of(bytes.fromhex(GX + GY))
G_CHECKSUM = checksum(G_ADDRESS)

require("pin d the address is 20 bytes", len(G_ADDRESS) == 40)
require("pin d the address of G", G_ADDRESS == "7e5f4552091a69125d5dfcb7b8c2659029395bdf")
require(
    "pin d the EIP-55 address of G",
    G_CHECKSUM == "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
)
require(
    "pin d the 04 prefix is dropped",
    address_of(bytes.fromhex("04" + GX + GY)[1:]) == G_ADDRESS,
)

pin("pin d the address of G", [G_ADDRESS])
pin("pin d the EIP-55 address of G", [G_CHECKSUM])

# ---------- pin (e): the eight EIP-55 reference strings ----------

EIP55 = [
    "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed",
    "0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359",
    "0xdbF03B407c01E7cD3CBea99509d93f8DDDC8C6FB",
    "0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9aDb",
    "0x52908400098527886E0F7030069857D2E4169EE7",
    "0x8617E340B3D01FA5F11F306F4090FD50E238070D",
    "0xde709f2102306220921060314715629080e2fb77",
    "0x27b1fdb04752bbc536007a920d24acb045561c26",
]

require("pin e the reference count", len(EIP55) == 8)

for index, want in enumerate(EIP55, 1):
    body = want[2:].lower()
    got = checksum(body)
    require(f"pin e reference {index} recomputes", got == want)
    pin(f"pin e the EIP-55 reference string {index}", [got])

# ---------- the negative controls ----------

twin = EMPTY_KECCAK[:-1] + format(int(EMPTY_KECCAK[-1], 16) ^ 1, "x")
if twin == EMPTY_KECCAK:
    print("diff_keccak: negative control is broken: the twin equals the pin")
    fail = 1
elif twin in STRIPPED:
    print(
        "diff_keccak: negative control FAILED: the corrupted twin of the empty "
        "keccak digest is present"
    )
    print(f"  twin: {twin}")
    fail = 1
else:
    print(
        "diff_keccak: negative control ok, the corrupted twin of the empty "
        "keccak digest is absent"
    )

# The second control proves the label stripping on a row held in memory:
# a digest that sits only in the row NAME must be reported MISSING, so a
# pin parked in a label can never satisfy this oracle.
SYNTH_ROW = f'  ( "{EMPTY_KECCAK} sits only in this label",\n    true );'
SYNTH_BODY = LABEL.sub("", SYNTH_ROW, count=1)
if EMPTY_KECCAK not in SYNTH_ROW:
    print("diff_keccak: label control is broken: the synthetic row holds no digest")
    fail = 1
elif EMPTY_KECCAK in SYNTH_BODY:
    print(
        "diff_keccak: label control FAILED: a value in a row label survives the strip"
    )
    fail = 1
else:
    print(
        "diff_keccak: label control ok, a value parked in a row name is not found"
    )

sys.exit(fail)
